### ISSUE TITLE
Additional frameworks

### ISSUE THREAD

**Issue by darshandsoni** [dohliam/dropin-minimal-css#1]
Don't have some spare time at this point to fork and PR, but in future you may want to add:

* [Basscss](http://basscss.com/)
* [Concise CSS](http://concisecss.com/)
* [Furtive](http://furtive.co/)

**Comment by dohliam** [comment]
Thanks for this! Hadn't heard of these before... will add them in ASAP :+1:

**Comment by dohliam** [comment]
Done! Unfortunately Basscss could not be added since it [only uses custom classes](https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/basscss/8.0.3/css/basscss.css) and so isn't really a drop-in CSS framework. Feel free to re-open this at a later point if you want to modify the Basscss classes to work out of the box!
